---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: restic_client.debian11-custom_user_group
    image: geerlingguy/docker-debian11-ansible:latest  # debian 11 - bullseye
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true

  - name: restic_client.debian12-custom_user_group
    image: geerlingguy/docker-debian12-ansible:latest  # debian 12 - bookworm
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true

  - name: restic_client.ubuntu1804-custom_user_group
    image: geerlingguy/docker-ubuntu1804-ansible:latest  # ubuntu 18.04 - bionic
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true

  - name: restic_client.ubuntu2004-custom_user_group
    image: geerlingguy/docker-ubuntu2004-ansible:latest  # ubuntu 20.04 - focal
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true

  - name: restic_client.ubuntu2204-custom_user_group
    image: geerlingguy/docker-ubuntu2204-ansible:latest  # ubuntu 22.04 - jammy
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true

  - name: restic_client.rockylinux8-custom_user_group
    image: geerlingguy/docker-rockylinux8-ansible:latest  # Rocky Linux 8
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true

  - name: restic_client.rockylinux9-custom_user_group
    image: geerlingguy/docker-rockylinux9-ansible:latest  # Rocky Linux 9
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
