---

- name: Clean up temporary downloads
  ansible.builtin.file:
    path: "/tmp/restic_{{ _restic_client_version }}_linux_*"
    state: absent
  delegate_to: localhost
  become: false

###
# Reloading this service is not supported on all distros
###
- name: Restart LVM event listener
  ansible.builtin.systemd:
    name: dm-event.service
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon-reload: true

- name: Enable systemd timers for restic service (on non-remote clients)
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - restic-backup.timer
    - restic-prune.timer
  when:
    - not restic_client_is_remote

###
# Only important in case a client is to be converted from local to remote
###
- name: Disable systemd timers for restic service (on remote clients)
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - restic-backup.timer
    - restic-prune.timer
  when:
    - restic_client_is_remote
