---

- name: Converge
  hosts: all

  vars:
    restic_client_encryption_password: "{{ lookup('passwordstore', 'IT/backup/encryption/' + inventory_hostname + ' create=true length=52') }}"
    ### We can't test LVM behaviour inside containers, it would use the hosts LVM.
    restic_client_use_lvm: false
    restic_client_repository: "templates/repository.exampleREST.j2"
    ### Vars for the sake of completeness and successful molecule run, after we
    ### defined our custom repository file above.
    restic_fifty2_backup_server: backup.example.com
    restic_fifty2_backup_server_port: 3000
    restic_fifty2_rest_username: "{{ inventory_hostname }}"
    restic_fifty2_rest_password: "{{ lookup('passwordstore', 'IT/backup/auth/' + inventory_hostname + ' create=true nosymbols=true') }}"
    restic_client_no_log: false

  tasks:
    - name: "Include molecule-custom_repository-scenario"
      ansible.builtin.include_role:
        name: "fifty2technology.restic_client"
