---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: restic_client.debian11-custom_repository
    image: docker.io/geerlingguy/docker-debian11-ansible:latest  # debian 11 - bullseye
    tmpfs:
      /tmp: exec
      /run: rw,noexec,nosuid,nodev
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true

  - name: restic_client.debian12-custom_repository
    image: docker.io/geerlingguy/docker-debian12-ansible:latest  # debian 12 - bookworm
    tmpfs:
      /tmp: exec
      /run: rw,noexec,nosuid,nodev
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true

  - name: restic_client.debian13-custom_repository
    image: docker.io/geerlingguy/docker-debian13-ansible:latest  # debian 13 - trixie
    tmpfs:
      /tmp: exec
      /run: rw,noexec,nosuid,nodev
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true

  - name: restic_client.ubuntu2004-custom_repository
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible:latest  # ubuntu 20.04 - focal
    tmpfs:
      /tmp: exec
      /run: rw,noexec,nosuid,nodev
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true

  - name: restic_client.ubuntu2204-custom_repository
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest  # ubuntu 22.04 - jammy
    tmpfs:
      /tmp: exec
      /run: rw,noexec,nosuid,nodev
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true

  - name: restic_client.ubuntu2404-custom_repository
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible:latest  # ubuntu 24.04 - noble
    tmpfs:
      /tmp: exec
      /run: rw,noexec,nosuid,nodev
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true

  - name: restic_client.rockylinux9-custom_repository
    image: docker.io/geerlingguy/docker-rockylinux9-ansible:latest  # Rocky Linux 9
    tmpfs:
      /tmp: exec
      /run: rw,noexec,nosuid,nodev
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true

  - name: restic_client.rockylinux10-custom_repository
    image: docker.io/geerlingguy/docker-rockylinux10-ansible:latest  # Rocky Linux 10
    tmpfs:
      /tmp: exec
      /run: rw,noexec,nosuid,nodev
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible
