---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: restic_client.debian11-custom_repository
    image: geerlingguy/docker-debian11-ansible:latest  # debian 11 - bullseye
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true

  - name: restic_client.debian12-custom_repository
    image: geerlingguy/docker-debian12-ansible:latest  # debian 12 - bookworm
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true

  - name: restic_client.debian13-custom_repository
    image: geerlingguy/docker-debian13-ansible:latest  # debian 13 - trixie
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true

  - name: restic_client.ubuntu2204-custom_repository
    image: geerlingguy/docker-ubuntu2204-ansible:latest  # ubuntu 22.04 - jammy
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true

  - name: restic_client.ubuntu2404-custom_repository
    image: geerlingguy/docker-ubuntu2404-ansible:latest  # ubuntu 24.04 - noble
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true

  - name: restic_client.rockylinux9-custom_repository
    image: geerlingguy/docker-rockylinux9-ansible:latest  # Rocky Linux 9
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true

  - name: restic_client.rockylinux10-custom_repository
    image: geerlingguy/docker-rockylinux10-ansible:latest  # Rocky Linux 10
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true

provisioner:
  name: ansible
verifier:
  name: ansible
