---

- name: Converge
  hosts: all

  vars:
    restic_client_encryption_password: "verybadpasswordexampleonlyuseformoleculerun"
    ### We can't test LVM behaviour inside containers, it would use the hosts LVM.
    restic_client_use_lvm: false

  tasks:
    - name: "Include molecule-default-scenario"
      ansible.builtin.include_role:
        name: "fifty2technology.restic_client"
