---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: restic_client.debian11-default
    image: docker.io/geerlingguy/docker-debian11-ansible:latest  # debian 11 - bullseye
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true

  - name: restic_client.debian12-default
    image: docker.io/geerlingguy/docker-debian12-ansible:latest  # debian 12 - bookworm
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true

  - name: restic_client.debian13-default
    image: docker.io/geerlingguy/docker-debian13-ansible:latest  # debian 13 - trixie
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true

  - name: restic_client.ubuntu2204-default
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest  # ubuntu 22.04 - jammy
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true

  - name: restic_client.ubuntu2404-default
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible:latest  # ubuntu 24.04 - noble
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true

  - name: restic_client.rockylinux9-default
    image: docker.io/geerlingguy/docker-rockylinux9-ansible:latest  # Rocky Linux 9
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true

  - name: restic_client.rockylinux10-default
    image: docker.io/geerlingguy/docker-rockylinux10-ansible:latest  # Rocky Linux 10
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true

provisioner:
  name: ansible
verifier:
  name: ansible
